// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SelectFilterController from "./select_filter_controller.js"
application.register("select-filter", SelectFilterController)

import StoreManagerController from "./store/manager_controller.js"
application.register("storemanager", StoreManagerController)

import TextareaAutogrow from "stimulus-textarea-autogrow"
application.register("textarea-autogrow", TextareaAutogrow)

import NestedForm from "stimulus-rails-nested-form"
application.register("nested-form", NestedForm)

import CovidController from "./covid_controller.js"
application.register("covid", CovidController)

import BootstrapController from "./bootstrap_controller.js"
application.register("bootstrap", BootstrapController)

import UploadsController from "./uploads_controller.js"
application.register("uploads", UploadsController)