BylawArticle.create!([
  {roman_numeral: "I", title: "Meetings", introduction: "", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "II", title: "Directors", introduction: "", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "III", title: "Officers", introduction: "", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "IV", title: "CORPORATE SEAL, EXECUTION OF ", introduction: "The organization shall not have a corporate seal. All instruments that are executed on behalf of the organization which are acknowledged and which affect an interest in real estate shall be executed by the President; or Vice President and the Secretary or Treasurer. All other instruments executed by the organization, including a release of mortgage or lien, may be executed by the President or Vice President. Notwithstanding the preceding provisions of this section, any written instrument may be executed by any officer(s) or agent(s) that are specifically designated by resolution of the Board of Directors.", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "V", title: "AMENDMENT TO BYLAWS", introduction: "The bylaws may be  amended, altered, or repealed by the Board of Directors by a two-thirds (2/3) majority of a quorum vote at any regular or special meeting. The text of the proposed change shall be distributed to all board members at least two (2) days before the meeting.", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "VI", title: "INDEMNIFICATION", introduction: "Any director or officer who is involved in litigation by reason of their position as a director or officer of this organization shall be indemnified and held harmless by the organization to the fullest extent authorized by law as it now exists or may subsequently be amended (but in the case of any such amendment, only to the extent that such amendment permits the organization to provide broader indemnification rights).", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"},
  {roman_numeral: "VII", title: "DISSOLUTION", introduction: "The organization may be dissolved with authorization of its Board of Directors given at a special meeting called for that purpose, and with the subsequent approval by no less than two-thirds (2/3) vote of the members. In the event of the dissolution of the organization, the assets shall be applied and distributed as follows:\n\nAll liabilities and obligations shall be paid, satisfied and discharged, or adequate provision shall be made therefore. Assets not held upon a condition requiring return, transfer, or conveyance to any other organization or individual shall be distributed, transferred, or conveyed, in trust or otherwise, to charitable and educational organization, organized under Section 501(c)(3) of the Internal Revenue Code of 1986, as amended, of a similar or like nature to this organization, as determined by the Board of Directors.\n", bylaw_id: "9dbf6d50-a386-4b15-817a-9275a08f7145"}
])
